### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by mohitajwani** [FireZenk/maven-repo#1]
Hi @FireZenk(Jorge),

Thanks a lot for making this repo and keeping the image crop library aar file. It was very helpful of you to do so. I was working on a project which was using this library and today I saw that this library was deprecated and my build failed. I then searched and found you repo and replaced my dependency with aar file.

P.S.: I did not know how to thank you, so I created this issue. You can close it once you have seen.

Thanks again.

**Comment by FireZenk** [comment]
Hahaha you're welcome 😃

**Comment by FireZenk** [comment]
You can also consume the dependency as always using Maven, simply by adding this to your gradle file:
```groovy
repositories {
  ...
  maven { url 'https://github.com/FireZenk/maven-repo/raw/master/'}
}
```

**Comment by mohitajwani** [comment]
Sure. Thanks.
